### ISSUE TITLE
Delayed Ejection Mode

### ISSUE THREAD

**Issue by asilvan** [openSX70/openSX70-Arduino-main#15]
**Is your feature request related to a problem? Please describe.**
Polaroid film is still light sensitive the minutes after the film is ejected from the camera. Users can install a "frog tongue" in their cameras to avoid immediate exposure to the light, but those tend to be flimsy and can introduce other issues.

**Describe the solution you'd like**
A solution for this problem would be a "delayed ejection" mode for the OpenSX-70. When enabled, this mode would result in the film not being ejected immediately after the film was exposed. Instead, the camera would wait for the shutter button to be release to eject the film.
This would give the photographer enough time to place the film exit inside their jacket, bag or maybe just have their dark slide ready to receive and cover the film.

**Additional context**
Since this feature might not be preferred by certain users, this mode should be gated by a feature flag in `settings.h`.

**Comment by asilvan** [comment]
I was able to implement this (it's a fairly small change).
I would like to have this feature enabled by default. Anyone disagree with having this as default?

**Comment by zanepollard** [comment]
I like the feature (as in I am more than likely gonna use it!!) but I feel it may be bad to deviate too far from the basic operation of the camera by default. 

Better to have it as an opt-in sort of thing in settings.h so people understand what they are enabling. That’s my view on it at least.

**Comment by asilvan** [comment]
Oh, good point! Agree.
I will keep it off by default then. Thank you!
